Repository Nowdays-Goodnight-Cool-Niang/Frontend, pull requests merged in 2025-04, with the labels that each got.

#38 [Bug] 빌드 에러 수정
  src/components/common/ProfileCard.tsx
  src/components/event/ParticipantCard.tsx
  src/components/event/ParticipantSection.tsx
  src/components/event/ShareCard.tsx
Labels: bug

#40 feat: 🎸 회원 탈퇴
  src/apis/accounts.ts
  src/components/mypage/MySection.tsx
Labels: action

#41 프로필 입력값 유효성 검증
  src/App.tsx
  src/apis/responseInterceptor.ts
  src/components/common/Input.tsx
  src/components/profile/FormContent.tsx
  src/components/profile/FormSection.tsx
  src/utils/form.ts
Labels: bug, action

#44 feat: 🎸 행사 프로필 저장 및 수정
  package-lock.json
  package.json
  src/apis/kakaoAuth.ts
  src/apis/participants.ts
  src/assets/fonts/PretendardVariable.woff2
  src/assets/images/img_share_card_graphic.png
  src/components/common/LayoutWithHeader.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/Modal.tsx
  src/components/common/NoticeInfo.tsx
  src/components/event/EditButton.tsx
  src/components/event/EventTabs.tsx
  src/components/event/ParticipantCard.tsx
  src/components/event/ParticipantSection.tsx
  src/components/event/ProfileSection.tsx
  src/components/event/ProfileText.tsx
  src/components/event/QRBox.tsx
  src/components/event/QRCameraSection.tsx
  src/components/event/ShareCard.tsx
  src/components/event/ShareCardInput.tsx
  src/components/event/ShareCardLabel.tsx
  src/components/event/SocialIcon.tsx
  src/components/event/SocialIcons.tsx
  src/components/profile/NoticeInfo.tsx
  src/enums/index.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useMutateShareCard.ts
  src/hooks/useQueryEventParticipants.ts
  src/hooks/useQueryShareCard.ts
  src/index.css
  src/pages/Event.tsx
  src/pages/Home.tsx
  src/pages/LoginRedirect.tsx
  src/pages/ProfileEdit.tsx
  src/pages/ProfileSetup.tsx
  src/stores/useProfileStore.tsx
  src/stores/useShareCardDetailStore.tsx
  src/types/index.ts
  src/types/response.ts
  src/utils/date.ts
  src/utils/event.ts
  src/utils/labels.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ui, action, refactor

#55 feat: 🎸 서비스 완성도 높이기
  index.html
  src/App.tsx
  src/apis/accounts.ts
  src/apis/auth.ts
  src/apis/kakaoAuth.ts
  src/apis/responseInterceptor.ts
  src/apis/shareCards.ts
  src/components/common/Header.tsx
  src/components/common/NoticeInfo.tsx
  src/components/common/ProfileCard.tsx
  src/components/event/EventTabs.tsx
  src/components/event/ParticipantSection.tsx
  src/components/event/ProfileSection.tsx
  src/components/event/ShareCard.tsx
  src/components/event/ShareCardInput.tsx
  src/components/event/SocialIcons.tsx
  src/components/mypage/MyProfile.tsx
  src/components/mypage/MySection.tsx
  src/components/profile/FormContent.tsx
  src/components/profile/FormSection.tsx
  src/hooks/useKakaoLogin.ts
  src/hooks/useMutateShareCard.ts
  src/hooks/useQueryAccount.ts
  src/hooks/useQueryEventParticipants.ts
  src/hooks/useQueryEventProfile.ts
  src/hooks/useQueryShareCard.ts
  src/mocks/api/data/profileData.ts
  src/mocks/api/profile.ts
  src/mocks/handlers.ts
  src/pages/Event.tsx
  src/pages/Home.tsx
  src/pages/LoginRedirect.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileEdit.tsx
  src/pages/ProfileSetup.tsx
  src/stores/useEventTabStore.ts
  src/stores/useParticipantProfileStore.ts
  src/stores/useShareCardDetailStore.tsx
  src/utils/labels.ts
  vite.config.ts
Labels: bug, refactor
