Repository Nowdays-Goodnight-Cool-Niang/Frontend, pull requests merged in 2025-03, with the labels that each got.

#20 feat: 🎸 홈(로그인) UI 제작
  src/assets/icons/ic_kakao.svg
  src/assets/images/img_geometric_graphic.png
  src/components/common/BaseButton.tsx
  src/components/common/Wrapper.tsx
  src/pages/Home.tsx
Labels: feat

#31 feat: 🎸 kakao 로그인 연결
  package-lock.json
  package.json
  public/mockServiceWorker.js
  public/phone.png
  public/profile_background.png
  public/vite.svg
  src/App.tsx
  src/apis/accounts.ts
  src/apis/events.ts
  src/apis/index.ts
  src/apis/kakaoAuth.ts
  src/apis/participants.ts
  src/apis/shareCards.ts
  src/assets/fonts/YdestreetB.ttf
  src/assets/icons/ic_edit.svg
  src/assets/icons/ic_github.svg
  src/assets/icons/ic_instagram.svg
  src/assets/icons/ic_linkedin.svg
  src/assets/images/img_share_card_graphic.png
  src/components/common/BaseButton.tsx
  src/components/common/ProfileCard.tsx
  src/components/common/Wrapper.tsx
  src/components/event/EventTab.tsx
  src/components/event/EventTabs.tsx
  src/components/event/ParticipantCard.tsx
  src/components/event/ParticipantSection.tsx
  src/components/event/ProfileSection.tsx
  src/components/event/ProfileText.tsx
  src/components/event/ShareCard.tsx
  src/components/event/ShareCardInput.tsx
  src/components/event/ShareCardLabel.tsx
  src/components/eventDetail/EventParticipants.tsx
  src/components/eventDetail/Header.tsx
  src/components/eventDetail/ParticipantCard.tsx
  src/components/eventDetail/Tab.tsx
  src/components/profile/FlyingCircles.tsx
  src/components/profile/ProfileInput.tsx
  src/components/profile/SNS.tsx
  src/enums/index.ts
  src/hooks/useQueryEvent.ts
  src/hooks/useQueryEventParticipants.ts
  src/hooks/useQueryEvents.tsx
  src/hooks/useQueryParticipantInfo.ts
  src/hooks/useQueryShareCard.ts
  src/index.css
  src/main.tsx
  src/mocks/api/data/shareCardData.ts
  src/mocks/api/shareCard.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/Event.tsx
  src/pages/Home.tsx
  src/pages/LoginRedirect.tsx
  src/pages/ProfileSetup.tsx
  src/stores/useEventTabStore.ts
  src/stores/useParticipantProfileStore.ts
  src/stores/useProfileStore.tsx
  src/types/index.ts
  tsconfig.app.json
  tsconfig.node.json
Labels: ui, action, refactor

#34 feat: 🎸 마이페이지 + 프로필 수정 UI
  src/App.tsx
  src/components/common/BaseButton.tsx
  src/components/common/SnsIcon.tsx
  src/components/event/ShareCard.tsx
  src/components/mypage/MyProfile.tsx
  src/components/mypage/MySection.tsx
  src/components/profile/FormSection.tsx
  src/index.css
  src/pages/ProfileEdit.tsx
Labels: ui, action

#35 feat: 🎸 프로필 조회 및 수정
  src/App.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/SnsIcon.tsx
  src/components/mypage/MyProfile.tsx
  src/components/mypage/MySection.tsx
  src/components/profile/FormContent.tsx
  src/components/profile/FormSection.tsx
  src/hooks/useQueryAccount.ts
Labels: ui, action
